In [5]:
import platform
from sklearn2pmml import sklearn2pmml
from imblearn.under_sampling import RandomUnderSampler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import preprocessing
import yaml
import sys
import argparse
from argparse import RawTextHelpFormatter
import numpy as np
sys.path.append("../../../")


In [6]:
def resamples(samples):
    x = np.vstack((samples['pos_samples']['X'],samples['neg_samples']['X']))
    y = np.vstack((samples['pos_samples']['X'],samples['neg_samples']['X']))
    print('采样前正负样本比例：正：负 = ',samples['pos_samples']['X'].shape[0],':',samples["neg_samples"]["X"].shape[0])
    rus = RandomUnderSampler(random_state=42, ratio={0.0 : int(1.1 * samples['pos_samples']['X'].shape[0])})
    x_res,y_res = rus.fit_sample(x,y)
    return x_res,y_res

In [9]:
b = np.array([[1, 2], [3, 4]])
print(np.tile(b, 2)) #沿X轴复制2倍
np.tile(b, (2, 1))#沿X轴复制1倍（相当于没有复制），再沿Y轴复制2倍

[[1 2 1 2]
 [3 4 3 4]]


array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [14]:
print(1, end="\r")

In [15]:
# dumps功能
import pickle
data = ['aa', 'bb', 'cc']  
# dumps 将数据通过特殊的形式转换为只有python语言认识的字符串
p_str = pickle.dumps(data)
print(p_str)            

b'\x80\x03]q\x00(X\x02\x00\x00\x00aaq\x01X\x02\x00\x00\x00bbq\x02X\x02\x00\x00\x00ccq\x03e.'


In [16]:
# loads功能
# loads  将pickle数据转换为python的数据结构
mes = pickle.loads(p_str)
print(mes)
# dump功能
# dump 将数据通过特殊的形式转换为只有python语言认识的字符串，并写入文件
with open(save_path, 'w') as f:
    pickle.dump(data, f)
# load功能
# load 从数据文件中读取数据，并转换为python的数据结构
with open(save_path, 'r') as f:
    data = pickle.load(f)

['aa', 'bb', 'cc']


In [18]:
c = np.array([[1,1],[1,2],[1,3],[1,4]])  
c.shape  
 
c.shape[0]  

c.shape[1]  

2

In [21]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
res = np.vstack((arr1, arr2))
print(res)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
res = np.hstack((arr1, arr2))
print(res)

arr1 = np.array([[1, 2], [3, 4], [5, 6]])
arr2 = np.array([[7, 8], [9, 0], [0, 1]])
res = np.hstack((arr1, arr2))
print(res)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 7 8]
 [3 4 9 0]
 [5 6 0 1]]


In [ ]:
def experiment(x,y ,algo="gbdt",params=None,df_path=None):
    x_train, x_test, y_train, y_test = None, None, None, None
    if df_path is None:
        x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=42)
        print('train samples dim', x_train.shape, 'test samples dim', x_test.shape)
        
        # 数据归一化
        min_max_scaler = preprocessing.MinMaxScaler().fit(x)
        

In [22]:
[{"title":"\u4e70\u5954\u9a70GLC\u6765\u8fd9\u770b\u5e95\u4ef7\uff0c\u8d2d\u8f66\u5e95\u4ef7\u4e00\u952e\u76f4\u8fbe","desc":"\u8c01\u8bf4\u597d\u8f66\u6ca1\u5e95\u4ef7\uff1f \u66f4\u5927\u7a7a\u95f4\uff0c\u66f4\u9ad8\u989c\u503c\uff0c\u66f4\u591a\u914d\u7f6e\uff0c\u54c1\u8d28SUV\u8f7b\u677e\u4e70\uff0c\u66f4\u591a\u4f18\u60e0\u5373\u523b\u77e5\u6653","image":{"material_id":["168"],"landingpage_url":[""],"deeplink_url":[""]}}]

[{'title': '买奔驰GLC来这看底价，购车底价一键直达',
  'desc': '谁说好车没底价？ 更大空间，更高颜值，更多配置，品质SUV轻松买，更多优惠即刻知晓',
  'image': {'material_id': ['168'],
   'landingpage_url': [''],
   'deeplink_url': ['']}}]

In [23]:
[{"image":{"material_id":["153"],"landingpage_url":[""],"deeplink_url":[""]}}]

[{'image': {'material_id': ['153'],
   'landingpage_url': [''],
   'deeplink_url': ['']}}]

In [24]:
[{"title":"\u805a\u201c\u4f17\u201d\u4eab\u597d\u793c","desc":"\u4e00\u6c7d-\u5927\u4f17\u9996\u4ed87888\u5143\u8d77","image":{"material_id":["4569"],"landingpage_url":[""],"deeplink_url":[""]}}]

[{'title': '聚“众”享好礼',
  'desc': '一汽-大众首付7888元起',
  'image': {'material_id': ['4569'],
   'landingpage_url': [''],
   'deeplink_url': ['']}}]

In [25]:
[{"title":"\u4e00\u6c7d-\u5927\u4f17","desc":"\u63a2\u5cb3\uff0c\u9996\u4ed83\u6210\uff0c2\u5e740\u5229\u7387\uff01","image":{"material_id":["4567"],"landingpage_url":[""],"deeplink_url":[""]}}]

[{'title': '一汽-大众',
  'desc': '探岳，首付3成，2年0利率！',
  'image': {'material_id': ['4567'],
   'landingpage_url': [''],
   'deeplink_url': ['']}}]

In [45]:
import yaml
config_param = yaml.load(open("E:\project\\201811\DSP\dsp\ctr/config.yml", "r", encoding="utf-8").read())
print(config_param)

{'workdir': {'Linux': '/data/kyy/workspace/ctr/hdfs_ctr/', 'Windows': 'E:/Work/jobs/data/DSP/CTR预估/samples/'}, 'defaultID': '99999999', 'window': 7, 'fields_use_strategy': {'history': True, 'realtime': True, 'personas': True, 'context': True, 'creativeTime': True}, 'xgboost': {'booster': 'gbtree', 'objective': 'binary:logistic', 'gamma': 0.1, 'max_depth': 4, 'lambda': 2, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 3, 'silent': 0, 'eta': 0.05, 'seed': 1000, 'nthread': 4, 'n_estimators': 50}, 'gbdt': {'loss': 'deviance', 'learning_rate': 0.1, 'n_estimators': 100}, 'xgboost_plus_lr': {'loss': 'deviance', 'learning_rate': 0.1, 'n_estimators': 100}, 'xgboost_plus_ffm': {'phase': 'train', 'xgboost': {'loss': 'deviance', 'learning_rate': 0.1, 'n_estimators': 30, 'max_depth': 3}, 'ffm': {'task': 'binary', 'lr': 0.2, 'lambda': 0.002, 'epoch': 20, 'metric': 'auc', 'k': 4}}, 'lightgbm_plus_ffm': {'phase': 'train', 'lightgbm': {'metric': 'binary_logloss', 'objective': 'binary', 

In [35]:
import argparse
from argparse import RawTextHelpFormatter

def parse_arguments(arguments):
    parser = argparse.ArgumentParser(description = 'ctr experiment',formatter_class=RawTextHelpFormatter)
    parser.add_argument('--channelid',required=True,default=4,help='渠道')
    parser.add_argument("--date", required=True, default="2018-08-09", help='样本截止日期')
    parser.add_argument("--phase", required=True, default="train",help='阶段选择，maybe train: train model, shallow: 生成浅层特征, complete:生成浅层+组合特征, scaler')
    try:
        arguments = parser.parse_args(args=arguments)
        arguments = vars(arguments)
    except:
        parser.print_help()
        sys.exit(0)
    print(arguments)
    

In [36]:
parse_arguments(config_param)

usage: ipykernel_launcher.py [-h] --channelid CHANNELID --date DATE --phase
                             PHASE

ctr experiment

optional arguments:
  -h, --help            show this help message and exit
  --channelid CHANNELID
                        渠道
  --date DATE           样本截止日期
  --phase PHASE         阶段选择，maybe train: train model, shallow: 生成浅层特征, complete:生成浅层+组合特征, scaler


usage: ipykernel_launcher.py [-h] --channelid CHANNELID --date DATE --phase
                             PHASE
ipykernel_launcher.py: error: the following arguments are required: --channelid, --date, --phase


SystemExit: 0

E:\Anaconda2\envs\Python3\lib\site-packages\IPython\core\interactiveshell.py:2971: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [39]:
[{"title":"\u5965\u8feaA4L \u9996\u4ed85.86\u4e07\u8d77","description":"\u5965\u8feaA4L \u9996\u4ed85.86\u4e07\u8d77\uff0c18\u671f0\u5229\u7387\u9650\u65f6\u7279\u4f9b","brandName":"\u4e00\u6c7d-\u5927\u4f17\u5965\u8fea","logo":{"material_id":["2684"],"landingpage_url":[""],"deeplink_url":[""]},"image":{"material_id":["2685"],"landingpage_url":[""],"deeplink_url":[""]}}]

[{'title': '奥迪A4L 首付5.86万起',
  'description': '奥迪A4L 首付5.86万起，18期0利率限时特供',
  'brandName': '一汽-大众奥迪',
  'logo': {'material_id': ['2684'],
   'landingpage_url': [''],
   'deeplink_url': ['']},
  'image': {'material_id': ['2685'],
   'landingpage_url': [''],
   'deeplink_url': ['']}}]

In [40]:
[{"title":"\u6211\u7684\u4fe1\u7528\uff0c\u80fd\u501f\u591a\u5c11\u94b1\uff1f","description":"\u8f7b\u677e\u501f\u6b3e \u5feb\u901f\u5230\u8d26","brandName":"360\u501f\u6761","logo":{"material_id":["2324"],"landingpage_url":[""],"deeplink_url":[""]},"image":{"material_id":["2393"],"landingpage_url":[""],"deeplink_url":[""]}}]

[{'title': '我的信用，能借多少钱？',
  'description': '轻松借款 快速到账',
  'brandName': '360借条',
  'logo': {'material_id': ['2324'],
   'landingpage_url': [''],
   'deeplink_url': ['']},
  'image': {'material_id': ['2393'],
   'landingpage_url': [''],
   'deeplink_url': ['']}}]

In [38]:
[{"title":"\u957f\u5b89\u9a6c\u81ea\u8fbe","desc":"\u8d2d\u8f66\u4eab\u4e24\u5e74\u53cc0\u7279\u60e0\uff0c\u7f6e\u6362\u8865\u8d34\u9ad8\u8fbe3000\u5143","quality_level":"1","display_labels":"\u4f18\u60e0","logo":{"material_id":["416"],"landingpage_url":[""],"deeplink_url":[""]},"image":{"material_id":["417","418","419"],"landingpage_url":["","",""],"deeplink_url":["","",""]}}]

[{'title': '长安马自达',
  'desc': '购车享两年双0特惠，置换补贴高达3000元',
  'quality_level': '1',
  'display_labels': '优惠',
  'logo': {'material_id': ['416'],
   'landingpage_url': [''],
   'deeplink_url': ['']},
  'image': {'material_id': ['417', '418', '419'],
   'landingpage_url': ['', '', ''],
   'deeplink_url': ['', '', '']}}]

In [14]:
import time
i=13
from_dt = time.strftime("%Y-%m-%d", time.localtime(int(time.time() - (i+1) * 60 * 60 * 24)))
to_dt = time.strftime("%Y-%m-%d", time.localtime(int(time.time() - i * 60 * 60 * 24)))
print(from_dt,to_dt)

2018-11-28 2018-11-29


In [105]:
i = 7
while i > 0:
#     match(i)
    print(i)
    i = i-1

7
6
5
4
3
2
1


In [128]:
for i in range(1,3):
    date = time.strftime("%Y-%m-%d", time.localtime(int(time.time() - i * 60 * 60 * 24)))
    print("select distinct imei,mediadata from t2pdm_data.t05_chehui_dsp_log_v2 where (etl_dt = '" + date + "') and channelid = 4  and length(imei)>5")
    print(i)

select distinct imei,mediadata from t2pdm_data.t05_chehui_dsp_log_v2 where (etl_dt = '2018-12-06') and channelid = 4  and length(imei)>5
1
select distinct imei,mediadata from t2pdm_data.t05_chehui_dsp_log_v2 where (etl_dt = '2018-12-05') and channelid = 4  and length(imei)>5
2


In [114]:
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/10/16 9:35
# @Author  : Yang Yuhan
import pandas as pd
df = pd.read_csv('E:\\project\\201812\\match_imei\\label.csv',encoding='utf-8')

In [116]:
df.head()

imei        娱乐        科技        购物        生活        商务  \
0  862471032417214  0.733974  0.741026  0.789744  0.963462  0.933974   
1  869927026280515  0.761905  0.802778  0.739087  0.801190  0.864484   
2  862097039674216  0.761979  0.765625  0.786458  0.802083  0.895312   
3  862183033009276  0.779630  0.826852  0.829630  0.875000  0.765741   
4  861530032137030  0.770833  0.700000  0.787500  0.804167  0.862500   

         时尚        旅游        游戏        财经   ...          汽车  美容  母婴育儿  电影  搞笑  \
0  0.932051  0.704487  0.726282  0.867308   ...    0.980000   0     0   0   0   
1  0.859127  0.818849  0.846825  0.824008   ...    0.916270   0     0   0   0   
2  0.882812  0.814063  0.694792  0.802083   ...    0.945833   0     0   0   0   
3  0.896296  0.795370  0.824074  0.808333   ...    0.901852   0     0   0   0   
4  0.787500  0.916667  0.833333  0.829167   ...    0.804167   0     0   0   0   

   健康  教育  音乐  资讯  source  
0   0   0   0   0   youku  
1   0   0   0   0   youku  
2   0   0   0   0   youku  
3   0   0   0   0   youku  
4   0   0   0   0   youku  

[5 rows x 23 columns]

In [117]:
df1 = df.groupby('imei').max()

In [118]:
df1.head()

娱乐        科技        购物        生活        商务        时尚  \
imei                                                                          
351673070295240  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
351702070977935  0.741667  0.783333  0.804167  0.766667  0.900000  0.845833   
351702071721712  0.771212  0.775758  0.637121  0.934848  0.789394  0.809091   
351702072957067  1.000000  1.000000  0.000000  1.000000  0.000000  1.000000   
351702075795373  0.788675  0.800641  0.759402  0.835256  0.870940  0.891453   

                       旅游        游戏        财经        女性   ...          汽车  美容  \
imei                                                      ...                   
351673070295240  1.000000  0.000000  0.000000  0.000000   ...    0.000000   0   
351702070977935  0.866667  0.820833  0.866667  0.858333   ...    0.937500   0   
351702071721712  0.713636  0.661364  0.902273  0.980000   ...    0.980000   0   
351702072957067  0.000000  0.000000  0.000000  0.000000   ...    0.000000   0   
351702075795373  0.778632  0.755128  0.804701  0.913675   ...    0.979701   0   

                 母婴育儿  电影  搞笑  健康  教育  音乐  资讯  source  
imei                                                   
351673070295240     0   0   0   0   0   0   0    momo  
351702070977935     0   0   0   0   0   0   0   youku  
351702071721712     0   0   0   0   0   0   0   youku  
351702072957067     0   1   0   0   1   0   0    momo  
351702075795373     0   0   0   0   0   0   0   youku  

[5 rows x 22 columns]

In [120]:
df1.to_csv('E:\\project\\201812\\match_imei\\label1.csv',encoding='utf-8')

In [55]:
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/10/16 9:35
# @Author  : Yang Yuhan
import pandas as pd
df = pd.read_csv('E:\\project\\201812\\ctr_compare\\raw.csv',encoding='utf-8')

In [56]:
df.head(20)


Unnamed: 0  precision       recall  f1-score  support
0           NaN        NaN          NaN       NaN      NaN
1      exposure       0.66         0.47      0.55    35395
2         click       0.57         0.75      0.65    33462
3           NaN        NaN          NaN       NaN      NaN
4      microavg        0.6          0.6       0.6    68857
5      macroavg       0.61         0.61       0.6    68857
6   weightedavg       0.62          0.6      0.59    68857
7           NaN        NaN          NaN       NaN      NaN
8    ==========   auc-test   ==========       NaN      NaN
9   0.652553335        NaN          NaN       NaN      NaN
10         test   logloss:  0.664574014       NaN      NaN
11          NaN  precision       recall  f1-score  support
12          NaN        NaN          NaN       NaN      NaN
13     exposure       0.61         0.78      0.69    35395
14        click       0.67         0.48      0.56    33462
15          NaN        NaN          NaN       NaN      NaN
16     microavg       0.63         0.63      0.63    68857
17     macroavg       0.64         0.63      0.62    68857
18  weightedavg       0.64         0.63      0.63    68857
19          NaN        NaN          NaN       NaN      NaN

In [91]:
# df = df.dropna(axis=0,how='any')
# tmp = []
for i in range(1):
    print(i)
#     tmp = df[]

0


In [58]:
df.head(20)

Unnamed: 0 precision recall f1-score support
1      exposure      0.66   0.47     0.55   35395
2         click      0.57   0.75     0.65   33462
4      microavg       0.6    0.6      0.6   68857
5      macroavg      0.61   0.61      0.6   68857
6   weightedavg      0.62    0.6     0.59   68857
13     exposure      0.61   0.78     0.69   35395
14        click      0.67   0.48     0.56   33462
16     microavg      0.63   0.63     0.63   68857
17     macroavg      0.64   0.63     0.62   68857
18  weightedavg      0.64   0.63     0.63   68857
25     exposure      0.64   0.69     0.67   35395
26        click      0.64   0.59     0.62   33462
28     microavg      0.64   0.64     0.64   68857
29     macroavg      0.64   0.64     0.64   68857
30  weightedavg      0.64   0.64     0.64   68857
37     exposure      0.64   0.71     0.67   35395
38        click      0.65   0.57     0.61   33462
40     microavg      0.64   0.64     0.64   68857
41     macroavg      0.64   0.64     0.64   68857
42  weightedavg      0.64   0.64     0.64   68857

In [70]:
df.to_csv('E:\\project\\201812\\ctr_compare\\test.csv',encoding='utf-8',index=False,sep='\t',header=False)

In [115]:
list(map(lambda x: 0.0 if math.isnan(x) else x, oldlist))
a = [x for x in pre if math.isnan(x)]

1
2
3


In [86]:
df_pos = df[df['field'] == 0]
df_neg = df[df['field'] != 0]
frac = 1
df_neg1 = df_neg.sample(frac=min(1.0, (df_pos.shape[0] * frac * 1.1 + frac + 1) / df_neg.shape[0]))

In [98]:
import numpy as np
print(df_neg1['field'].values + 0.22)
df_neg1[df_neg1['field'] == 2] =np.around(0.2222,2)
print(df_neg1['field'])

[ 0.44 24.22  3.22 10.22 24.22 18.22  6.22  9.22]
208     0.22
293    24.00
42      3.00
122    10.00
292    24.00
217    18.00
74      6.00
113     9.00
Name: field, dtype: float64


In [101]:
a = [1,0,0,0,1]
[min(1,i+0.22) for i in a]

[1, 0.22, 0.22, 0.22, 1]

In [82]:
df.values.T.tolist()

[['exposure',
  'click',
  'microavg',
  'macroavg',
  'weightedavg',
  'exposure',
  'click',
  'microavg',
  'macroavg',
  'weightedavg',
  'exposure',
  'click',
  'microavg',
  'macroavg',
  'weightedavg',
  'exposure',
  'click',
  'microavg',
  'macroavg',
  'weightedavg',
  'exposure',
  'click',
  'microavg',
  'macroavg',
  'weightedavg',
  'exposure',
  'click',
  'microavg',
  'macroavg',
  'weightedavg',
  'exposure',
  'click',
  'microavg',
  'macroavg',
  'weightedavg',
  'exposure',
  'click',
  'microavg',
  'macroavg',
  'weightedavg',
  'exposure',
  'click',
  'microavg',
  'macroavg',
  'weightedavg',
  'exposure',
  'click',
  'microavg',
  'macroavg',
  'weightedavg',
  'exposure',
  'click',
  'microavg',
  'macroavg',
  'weightedavg',
  'exposure',
  'click',
  'microavg',
  'macroavg',
  'weightedavg',
  'exposure',
  'click',
  'microavg',
  'macroavg',
  'weightedavg',
  'exposure',
  'click',
  'microavg',
  'macroavg',
  'weightedavg',
  'exposure',
  'cli

In [62]:
lists =[]
for i in range(28):
    for j in range(0,5):
        idx = i*5+j
        lists.append(i)

In [28]:
df.head(20)

Unnamed: 0 precision recall f1-score support  field
1      exposure      0.66   0.47     0.55   35395      0
2         click      0.57   0.75     0.65   33462      0
4      microavg       0.6    0.6      0.6   68857      0
5      macroavg      0.61   0.61      0.6   68857      0
6   weightedavg      0.62    0.6     0.59   68857      0
13     exposure      0.61   0.78     0.69   35395      1
14        click      0.67   0.48     0.56   33462      1
16     microavg      0.63   0.63     0.63   68857      1
17     macroavg      0.64   0.63     0.62   68857      1
18  weightedavg      0.64   0.63     0.63   68857      1
25     exposure      0.64   0.69     0.67   35395      2
26        click      0.64   0.59     0.62   33462      2
28     microavg      0.64   0.64     0.64   68857      2
29     macroavg      0.64   0.64     0.64   68857      2
30  weightedavg      0.64   0.64     0.64   68857      2
37     exposure      0.64   0.71     0.67   35395      3
38        click      0.65   0.57     0.61   33462      3
40     microavg      0.64   0.64     0.64   68857      3
41     macroavg      0.64   0.64     0.64   68857      3
42  weightedavg      0.64   0.64     0.64   68857      3

In [44]:
with open('E:\\project\\201812\\ctr_compare\\featuresNames.txt', "r", encoding="utf-8") as file_read:
    data = [line.split(',') for line in file_read]


    

In [53]:
data

[['4',
  'interest:10001',
  'interest:10002',
  'interest:10003',
  'interest:10004',
  'interest:10005',
  'interest:10006',
  'interest:10007',
  'interest:10008',
  'interest:10009',
  'interest:10010',
  'interest:10011',
  'interest:10012',
  'interest:10013',
  'interest:10014',
  'interest:99999999',
  'materialid:4118',
  'materialid:4119',
  'materialid:4120',
  'materialid:4122',
  'materialid:4123',
  'materialid:4124',
  'materialid:4294',
  'materialid:4296',
  'materialid:4297',
  'materialid:4409',
  'materialid:4412',
  'materialid:4415',
  'materialid:4451',
  'materialid:4453',
  'materialid:4456',
  'materialid:4532',
  'materialid:4533',
  'materialid:4534',
  'materialid:4541',
  'materialid:4542',
  'materialid:4543',
  'materialid:4553',
  'materialid:4554',
  'materialid:4555',
  'materialid:4571',
  'materialid:4572',
  'materialid:4573',
  'materialid:4575',
  'materialid:4576',
  'materialid:4577',
  'materialid:4582',
  'materialid:4584',
  'materialid:4585

In [50]:
field_name_dict = {}
for l in data:
    for it in l:
        field = it.split(':')[0]
        if field not in field_name_dict:
            field_name_dict[field] = len(field_name_dict)


In [51]:
len(field_name_dict)

27

In [52]:
field_name_dict

{'4': 0,
 'interest': 1,
 'materialid': 2,
 'desckws': 3,
 'adgroupid': 4,
 'adid': 5,
 'advertiserid': 6,
 'age': 7,
 'campaignid': 8,
 'createtype': 9,
 'creativeid': 10,
 'displaylabel': 11,
 'gender': 12,
 'height': 13,
 'hour': 14,
 'mobiletype': 15,
 'nettype': 16,
 'os': 17,
 'phonebrand': 18,
 'placeid': 19,
 'province': 20,
 'title': 21,
 'week': 22,
 'width': 23,
 'history': 24,
 'creativeTime_create': 25,
 'creativeTime_updated\n': 26}

In [ ]:
sc.setLogLevel("ERROR")
from pyspark.sql import HiveContext
sqlContext = HiveContext(sc)
df = sqlContext.sql("select * from t2pdm_data.t05_chehui_dsp_log_v2 limit 10")
df = sqlContext.sql("select * from usercenter_dw.yk2iqytag limit 10")

df = sqlContext.sql("select * from t2pdm_data.t05_chehui_dsp_log_v2 where etl_dt = '2018-12-15' and channelid=4 limit 10000")

In [ ]:
df.write.save("hdfs://bitautodmp/user/yangyuhan1/samples_4", format='parquet', mode='append')
df.write.mode("overwrite").options(header="true").csv("hdfs://bitautodmp/user/yangyuhan1/samples_4.csv")


In [133]:
p = 0.5
w1 =np.array([[-0.1,0.2],[0.3,0.4]])
h1 = np.maximum(0,w1)
u1 = np.random.rand(*h1.shape)<p
print(u1)
u1/p

[[ True False]
 [ True  True]]


array([[2., 0.],
       [2., 2.]])